-- =============================================================================
-- Telegram Integration: link tokens + linked accounts
-- =============================================================================

-- One-time tokens generated by the web app (expire after 10 min)
CREATE TABLE IF NOT EXISTS telegram_link_tokens (
  token       TEXT        PRIMARY KEY,
  user_id     UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at  TIMESTAMPTZ NOT NULL DEFAULT now() + interval '10 minutes'
);

CREATE INDEX IF NOT EXISTS idx_telegram_link_tokens_user ON telegram_link_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_telegram_link_tokens_expires ON telegram_link_tokens(expires_at);

-- Permanent Telegram ↔ Supabase user mapping
CREATE TABLE IF NOT EXISTS telegram_links (
  telegram_id  BIGINT      PRIMARY KEY,
  user_id      UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  username     TEXT,
  first_name   TEXT,
  linked_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id)
);

-- Ensure columns exist if table was created previously without them
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='telegram_links' AND column_name='username') THEN
        ALTER TABLE telegram_links ADD COLUMN username TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='telegram_links' AND column_name='first_name') THEN
        ALTER TABLE telegram_links ADD COLUMN first_name TEXT;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_telegram_links_user ON telegram_links(user_id);

-- RLS: authenticated users can manage their own tokens and read their own link
ALTER TABLE telegram_link_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE telegram_links ENABLE ROW LEVEL SECURITY;

-- Web app: user can insert / delete their own tokens
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'telegram_link_tokens' AND policyname = 'tlt_select') THEN
    CREATE POLICY tlt_select ON telegram_link_tokens FOR SELECT TO authenticated USING (user_id = auth.uid());
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'telegram_link_tokens' AND policyname = 'tlt_insert') THEN
    CREATE POLICY tlt_insert ON telegram_link_tokens FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'telegram_link_tokens' AND policyname = 'tlt_delete') THEN
    CREATE POLICY tlt_delete ON telegram_link_tokens FOR DELETE TO authenticated USING (user_id = auth.uid());
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'telegram_links' AND policyname = 'tl_select') THEN
    CREATE POLICY tl_select ON telegram_links FOR SELECT TO authenticated USING (user_id = auth.uid());
  END IF;
END $$;
