-- =============================================================================
-- Telegram Integration: link tokens + linked accounts
-- =============================================================================

-- One-time tokens generated by the web app (expire after 10 min)
CREATE TABLE telegram_link_tokens (
  token       TEXT        PRIMARY KEY,
  user_id     UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at  TIMESTAMPTZ NOT NULL DEFAULT now() + interval '10 minutes'
);

CREATE INDEX idx_telegram_link_tokens_user ON telegram_link_tokens(user_id);
CREATE INDEX idx_telegram_link_tokens_expires ON telegram_link_tokens(expires_at);

-- Permanent Telegram ↔ Supabase user mapping
CREATE TABLE telegram_links (
  telegram_id  BIGINT      PRIMARY KEY,
  user_id      UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  linked_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id)
);

CREATE INDEX idx_telegram_links_user ON telegram_links(user_id);

-- RLS: authenticated users can manage their own tokens and read their own link
ALTER TABLE telegram_link_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE telegram_links ENABLE ROW LEVEL SECURITY;

-- Web app: user can insert / delete their own tokens
CREATE POLICY tlt_select ON telegram_link_tokens FOR SELECT TO authenticated
  USING (user_id = auth.uid());
CREATE POLICY tlt_insert ON telegram_link_tokens FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());
CREATE POLICY tlt_delete ON telegram_link_tokens FOR DELETE TO authenticated
  USING (user_id = auth.uid());

-- Web app: user can read their own link status
CREATE POLICY tl_select ON telegram_links FOR SELECT TO authenticated
  USING (user_id = auth.uid());

-- Service role bypasses RLS (bot uses service_role key to write telegram_links
-- and to consume + delete telegram_link_tokens after linking)
